apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spara
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spara
    spec:
      containers:
      - image: localhost:5000/spara:0.0.6
        imagePullPolicy: Always
        name: spara
        env:
          - name: NODE_ENV
            value: production
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 60
