apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forsakra
  namespace: production
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: forsakra
    spec:
      containers:
      - image: localhost:5000/forsakra:0.0.2
        imagePullPolicy: Always
        name: forsakra
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
            #httpHeaders:
            #  - name: X-Custom-Header
            #    value: Awesome
          initialDelaySeconds: 5
          periodSeconds: 30
